name: Rust CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  ci:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        rust:
          - stable

    steps:
      # Checkout
      - name: Checkout
        uses: actions/checkout@v3
      # Toolchain
      - name: Toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: ${{ matrix.rust }}
          override: true
          components: rustfmt, clippy
      # Build
      - name: Build
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --verbose
      # Tests
      - name: Tests
        uses: actions-rs/cargo@v1
        with:
          command: test
      # Formatting
      - name: Formatting
        uses: actions-rs/cargo@v1
        with:
          command: fmt
          args: --all -- --check
      # Clippy
      - name: Clippy
        uses: actions-rs/cargo@v1
        with:
          command: clippy
          args: -- -D warnings